net/mlx5: remove deprecated modify header actions
This patch removes support for deprecated modify header actions in
queued rte_flow implementation.

This patch adds initialization for refmt_type variable declared in
flow_hw_actions_translate(). Removal of translation of deprecated modify
header actions caused build with "--werror --buildtype=debugoptimized"
options to fail with GCC on Armv8 with the following error:

error: ‘refmt_type’ may be used uninitialized in this function
        [-Werror=maybe-uninitialized]

This error is a false positive since:

- refmt_type is used if and only if reformat_pos is not equal to
UINT16_MAX,
- reformat_pos is always updated alongside refmt_type,
- removed code did not affect refmt_type and reformat_pos values.

Initialization of refmt_type to a valid enum value is added to prevent
this build error.

Signed-off-by: Dariusz Sosnowski <dsosnowski@nvidia.com>